### ISSUE TITLE
Collab request

### ISSUE THREAD

**Issue by krislauridsen** [PolarBean/Allen_Brain_Neuron_Finder#1]
Hi there @PolarBean, 

Myself and some other members of the Root Lab organization of the University of Colorado Boulder noticed a few of your projects including DeepSlice and CellfHelp with some excitement as it appears there is a lot of similarity between your work and our work for the analysis of brain imaging data. 

Here is the contact of myself and a colleague if you are interested in any sort of collaboration moving forward. 

Kris Lauridsen (myself): krla4249@colorado.edu
Gunnar Enserro: guen1727@colorado.edu

**Comment by PolarBean** [comment]
Dear Kris,

Thank you for reaching out, I’ll be in touch!
